version: "3.8"

services:
  reverse-proxy:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml

  postgres:
    image: postgres:12-alpine
    container_name: postgres_bilim
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    env_file:
      - .env
    volumes:
      - ./app:/go/src/app
      - media:/go/src/app/media/
    depends_on:
      - postgres
      - reverse-proxy

  nginx:
    image: nginx:alpine
    volumes:
      - media:/usr/share/nginx/html/media:ro
      - ./config/static_server.nginx:/config/nginx/site-confs/default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/media`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

volumes:
  postgres-data:
  media:
