entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

accessLog:

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false
    watch: true
