# Generated by Django 3.1.13 on 2021-09-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'managed': False, 'ordering': ['order']},
        ),
    ]
